import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ApolloWrapper } from "@/lib/apollo-wrapper";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shoplify",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  if (process.env.NODE_ENV !== 'production') {
    const { loadErrorMessages, loadDevMessages } = require('@apollo/client/dev');
    loadErrorMessages();
    loadDevMessages();
  }
  return (
    <html lang="en">
      <body className={inter.className}>
      <ApolloWrapper>

        {children}
        
      </ApolloWrapper>
        </body>
    </html>
  );
}
